services:
  # 1. The PostgreSQL Database
  - type: pserv
    name: jobportal-db
    plan: free # You can upgrade this later
    postgres:
      version: "14"

  # 2. The NestJS Backend Service
  - type: web
    name: jobportal-backend
    plan: free
    env: node
    rootDir: ./backend # Tell Render to look inside the 'backend' folder
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL # Render provides this URL to connect to the database above
        fromService:
          type: pserv
          name: jobportal-db
          property: connectionString
      - key: DB_HOST
        fromService:
          type: pserv
          name: jobportal-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: jobportal-db
          property: port
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: jobportal-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: jobportal-db
          property: password
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: jobportal-db
          property: database
      - key: JWT_SECRET # You can generate a new, strong secret key here
        generateValue: true
      - key: JWT_RESET_SECRET
        generateValue: true
      - key: WEBSITE_OWNER_EMAIL
        value: trxtech746@gmail.com # Your email address

  # 3. The Next.js Frontend Service
  - type: web
    name: jobportal-frontend
    plan: free
    env: node
    rootDir: ./frontend # Tell Render to look inside the 'frontend' folder
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL # This will be the public URL of your backend service
        fromService:
          type: web
          name: jobportal-backend
          property: url